# Generated by Django 5.2.17 on 2026-09-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('jd_text', models.TextField()),
                ('resume_text_used', models.TextField()),
                ('used_stored_resume', models.BooleanField(default=True)),
                ('score', models.FloatField()),
                ('verdict', models.CharField(max_length=20)),
                ('primary_model', models.CharField(max_length=30)),
                ('other_model_score', models.FloatField()),
                ('other_model_verdict', models.CharField(max_length=20)),
                ('other_model_name', models.CharField(max_length=30)),
                ('matched_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('resume_years_experience', models.FloatField(null=True)),
                ('jd_years_experience_required', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('raw_text', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
